USE [Database_vendas]
GO

/****** Object:  Table [dbo].[TAB_VENDAS]    Script Date: 07/05/2024 23:50:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_VENDAS](
	[COD_VENDA] [int] NOT NULL,
	[COD_VENDED] [int] NOT NULL,
	[VAL_VENDA] [float] NULL,
	[VAL_DESCON] [float] NULL,
	[VAL_TOTAL] [float] NULL,
	[DAT_VENDA] [date] NULL,
 CONSTRAINT [PK_TB_VENDAS] PRIMARY KEY CLUSTERED 
(
	[COD_VENDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAB_VENDAS]  WITH CHECK ADD FOREIGN KEY([COD_VENDED])
REFERENCES [dbo].[TAB_VENDEDORES] ([COD_VENDED])
GO


