USE [Database_vendas]
GO

/****** Object:  Table [dbo].[TAB_VENDEDORES]    Script Date: 07/05/2024 23:51:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAB_VENDEDORES](
	[COD_VENDED] [int] NOT NULL,
	[NOM_VENDED] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_VENDED] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


